stages:
  preprocessing:
    cmd: python3 data_governance/code/preprocess.py '/data_governance/data/input/train.csv' '/data_governance/data/processed/train.parquet' 'Review'
    deps:
    - data_governance/code/preprocess.py
    - data_governance/data/input/train.csv
    outs:
    - data_governance/data/processed/train.parquet
  vectorize:
    cmd: python3 data_governance/code/vectorize.py '/data_governance/data/processed/train.parquet' '/data_governance/data/models/vectorizer.pickle' '/data_governance/data/features/train.parquet' '/data_governance/data/features/test.parquet'
    deps:
    - data_governance/code/vectorize.py
    - data_governance/data/processed/train.parquet
    outs:
    - data_governance/data/models/vectorizer.pickle
    - data_governance/data/features/train.parquet
    - data_governance/data/features/test.parquet
  apply_vectorizer:
    foreach:
      - train
      - test
    do:
      cmd: python3 data_governance/code/apply_vectorizer.py '/data_governance/data/features/${item}.parquet' '/data_governance/data/models/vectorizer.pickle' '/data_governance/data/prepared/${item}_features.npz' '/data_governance/data/prepared/${item}_target.npy'
      deps:
      - data_governance/code/apply_vectorizer.py
      - data_governance/data/features/${item}.parquet
      - data_governance/data/models/vectorizer.pickle
      outs:
      - data_governance/data/prepared/${item}_features.npz
      - data_governance/data/prepared/${item}_target.npy