stages:
  preprocessing:
    cmd: python3 data_governance/code/preprocess.py '/data_governance/data/input/train.csv' '/data_governance/data/processed/train.parquet' 'Review'
    deps:
    - data_governance/code/preprocess.py
    - data_governance/data/input/train.csv
    outs:
    - data_governance/data/processed/train.parquet
  vectorize:
    cmd: python3 data_governance/code/vectorize.py '/data_governance/data/processed/train.parquet' '/data_governance/data/models/vectorizer.pickle' '/data_governance/data/features/train.parquet' '/data_governance/data/features/test.parquet'
    params:
      - data_governance/params.yaml:
        - vectorizer_tfidf
        - random_state
        - test_train_split
    deps:
    - data_governance/code/vectorize.py
    - data_governance/data/processed/train.parquet
    outs:
    - data_governance/data/models/vectorizer.pickle
    - data_governance/data/features/train.parquet
    - data_governance/data/features/test.parquet
  apply_vectorizer:
    foreach:
      - train
      - test
    do:
      cmd: python3 data_governance/code/apply_vectorizer.py '/data_governance/data/features/${item}.parquet' '/data_governance/data/models/vectorizer.pickle' '/data_governance/data/prepared/${item}_features.npz' '/data_governance/data/prepared/${item}_target.npy'
      deps:
      - data_governance/code/apply_vectorizer.py
      - data_governance/data/features/${item}.parquet
      - data_governance/data/models/vectorizer.pickle
      outs:
      - data_governance/data/prepared/${item}_features.npz
      - data_governance/data/prepared/${item}_target.npy
  train_model:
    cmd: python3 data_governance/code/models.py '/data_governance/data/prepared/train_features.npz' '/data_governance/data/prepared/train_target.npy' '/data_governance/data/models/model.pickle'
    params:
    - data_governance/params.yaml:
      - logistic_regression
    deps:
    - data_governance/code/models.py
    - data_governance/data/prepared/train_features.npz
    - data_governance/data/prepared/train_target.npy
    outs:
    - data_governance/data/models/model.pickle
  evaluate:
    cmd: python3 data_governance/code/evaluate.py '/data_governance/data/prepared/test_features.npz' '/data_governance/data/prepared/test_target.npy' '/data_governance/data/models/model.pickle' '/data_governance/data/metrics/summary.json' '/data_governance/data/metrics/confusion_matrix.png'
    deps:
    - data_governance/code/evaluate.py
    - data_governance/data/prepared/test_features.npz
    - data_governance/data/prepared/test_target.npy
    - data_governance/data/models/model.pickle
    metrics:
    - data_governance/data/metrics/summary.json
    plots:
    - data_governance/data/metrics/confusion_matrix.png